yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

# Добавляем имена путям из приложения posts.
urlpatterns = [
    path('', views.index, name='posts_list'),
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'),
    # Просмотр профиля
    path('profile/<str:username>/',
         views.profile,
         name='profile'),
    # Просмотр поста
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'),
    # Создание поста
    path('create/',
         views.post_create,
         name='post_create'),
    # Редактирование поста
    path('posts/<post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    # Комментирование поста
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/urls.py
from django.urls import include, path

# Добавляем к путям из приложения posts пространства имен.
urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('group/<slug:slug>/', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls'))
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls')),
    path('group/<slug:slug>/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/card.html
{% load thumbnail %}
<article>
  <ul>
    <li>
      Автор: {{ post.author }}
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>
    {{ post.text }}
  </p>
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
</article>
{% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %}

yatube/templates/includes/footer.html
© {{ year }} Copyright <span style="color:red">Ya</span>tube

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:posts_list' %}">
      <img src="{% static 'img/logo.png' %}"
        width="30"
        height="30"
        class="d-inline-block align-top"
        alt="">
      <span style="color:red">Ya</span>tube</a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
            href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
            href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
              href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}"
              href="{% url 'users:password_change' %}">Изменить пароль</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
              href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>Пользователь: {{ user.username }}</li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
              href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
              href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      {% endwith %}
    </ul>
  </div>
</nav>