yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

# Добавляем имена путям из приложения posts.
urlpatterns = [
    path('', views.index, name='posts_list'),
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'),
    # Просмотр профиля
    path('profile/<str:username>/',
         views.profile,
         name='profile'),
    # Просмотр поста
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'),
    # Создание поста
    path('create/',
         views.post_create,
         name='post_create'),
    # Редактирование поста
    path('posts/<post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    # Комментирование поста
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/urls.py
from django.urls import include, path

# Добавляем к путям из приложения posts пространства имен.
urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('group/<slug:slug>/', include('posts.urls', namespace='posts')),
    path('auth/', include('django.contrib.auth.urls'))
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls')),
    path('group/<slug:slug>/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from .validators import validate_not_empty

User = get_user_model()


class Group(models.Model):
    """Модель сообществ.

    У сообществ есть название, адрес, описание и пользователь-создатель."""

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE
    )

    def __str__(self):
        """Дает название на страницах сообществ."""
        return self.title


class Post(models.Model):
    """Модель постов.

    У постов есть текст, картинка, дата публикации, сообщество,
    где пост опубликован, и пользователь-создатель."""

    text = models.TextField(validators=[validate_not_empty])
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        """Вывод текста поста."""
        return self.text[:15]


class Comment(models.Model):
    """Модель комментариев.

    У комментариев есть текст, пост, к которому относится
    комментарий, дата публикации и пользователь-создатель."""

    text = models.TextField(validators=[validate_not_empty])
    pub_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(
        Post,
        null=True,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        """Вывод текста комментария."""
        return self.text


class Follow(models.Model):
    """Модель подписок: автор контента и подписчик."""

    user = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        related_name='following'
    )

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    """Форма поста: текст, группа и картинка."""

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст',
            'group': 'Группа',
            'image': 'Картинка'
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
            'image': 'Прикрепите к посту изображение'
        }


class CommentForm(forms.ModelForm):
    """Форма комментария: текст."""

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm

LIMIT: int = 10


def index(request):
    """Создает главную страницу с пажинатором"""
    context = {
        'page_obj': create_pages(request,
                                 Post.objects.select_related('author',
                                                             'group').all()),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Страница с постами конкретной группы."""
    group = get_object_or_404(Group, slug=slug)
    context = {
        'group': group,
        'page_obj': create_pages(request,
                                 group.posts.select_related('author').all())
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Профиль пользователя."""
    author = get_object_or_404(User, username=username)
    if request.user.is_authenticated:
        context = {
            'author': author,
            'page_obj': create_pages(request,
                                     author.posts.select_related('group',
                                                                 ).all()),
            'following': Follow.objects.filter(user=request.user,
                                               author=author
                                               ).exists()
        }
    else:
        context = {
            'author': author,
            'page_obj': create_pages(request,
                                     author.posts.select_related('group',
                                                                 ).all())
        }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Страница просмотра поста."""
    post = get_object_or_404(Post, id=post_id)
    context = {
        'post': post,
        'form': CommentForm(request.POST or None),
        'comments': post.comments.select_related('author',).all()
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Cоздание поста."""
    form = PostForm(request.POST or None, files=request.FILES or None)
    if not form.is_valid():
        context = {
            'form': form
        }
        return render(request, 'create_post.html', context)
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', username=request.user)


@login_required
def post_edit(request, post_id):
    """Редактирование поста."""
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(instance=post,
                    files=request.FILES or None,
                    data=request.POST)
    if not form.is_valid():
        context = {
            'form': form,
            'is_edit': True
        }
        return render(request, 'create_post.html', context)
    form.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Страница с постами, на авторов которых подписан текущий пользователь"""
    context = {
        'page_obj': create_pages(
            request,
            Post.objects.select_related('author', 'group').filter(
                author__following__user=request.user
            ).all()),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Подписаться на автора"""
    author = get_object_or_404(User, username=username)
    if request.user == author:
        return redirect('posts:profile', username=username)
    Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Отписаться от автора"""
    author = get_object_or_404(User, username=username)
    if request.user == author:
        return redirect('posts:profile', username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)


def create_pages(request, post_list):
    """Получение страниц с пажинатором."""
    paginator = Paginator(post_list, LIMIT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Мои подписки{% endblock %}
{% block content %}
  <h1>Мои подписки</h1>
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
      <article>
        {% include 'includes/card.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      </article>
    {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Записи сообщества {{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    <hr>
  </div>
  <h1>{{ group }}</h1>
  {% for post in page_obj %}
    <article>
      {% include 'includes/card.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    </article>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% load cache %}
{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% include 'posts/includes/switcher.html' %}
  {% cache 20 index_page %}
    {% for post in page_obj %}
      <article>
        {% include 'includes/card.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      </article>
    {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group }}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          </li>
        {% endif %}
        <li class="list-group-item">Автор: {{ post.author }}</li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span>{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
        </li>
    </ul>
    </aside>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <article class="col-12 col-md-9">
      <p>
        {{ post.text }}
      </p>
    </article>
    {% if post.author == request.user %}
      <a href="{% url 'posts:post_edit' post.id %}">редактировать пост</a>
    {% endif %}
    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}
            <div class="form-group mb-2">
              {{ form.text }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}

    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
            <p>
             {{ comment.text }}
            </p>
          </div>
        </div>
    {% endfor %}
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block title %}Профайл пользователя {{ author }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author }}</h1>
      <h3>Всего постов: {{ author.posts.count }}</h3>
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    </div>
    {% for post in page_obj %}
      <article>
        {% include 'includes/card.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      </article>
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}